language: android
jdk: oraclejdk8

android:
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-26
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_script:
    - mkdir -p "$ANDROID_HOME/licenses"
    - cp ./google-licenses/* "$ANDROID_HOME/licenses/"
    - sys-img-armeabi-v7a-google_apis-25
    - echo no | android create avd --force -n test -t android-25 --abi google_apis/armeabi-v7a
    - emulator -avd test -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &
    - chmod +x ./gradlew
script:
  - ./gradlew build check
  - ./gradlew build jacocoTestReport assembleAndroidTest

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: lexfiapp@gmail.com