language: android
jdk: oraclejdk8

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
 
cache:
  directories:      #Cache all dirs under .gradle folder
    - $HOME/.gradle/daemon      #Cache daemon logs
    - $HOME/.gradle/native      #Cache library downloaded from the gradle dependency
    - $HOME/.gradle/wrapper     #Cache the gradle

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-25.0.2

    # The SDK version used to compile your project
    - android-16
    - android-21
    - android-22
    - android-23
    - android-25

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    # - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-16
    - sys-img-armeabi-v7a-android-21
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-23
    - sys-img-armeabi-v7a-android-25

licenses:
    - 'android-googletv-license-.+'
    - 'android-sdk-license-.+'
    - 'android-sdk-preview-license-.+'
    - 'google-gdk-license-.+'
    - 'android-sdk-license-.+'
    - 'intel-android-extra-license-.+'
    - 'mips-android-sysimage-license-.+'    -

script:
    - echo "Travis branch is $TRAVIS_BRANCH"
    - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"

before_install:
    - chmod +x gradlew

after_success:
    - ./gradlew jacocoTestReport coveralls

notifications:
  email: lexfiapp@gmail.com